apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksdemo-19f0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksdemo-19f0"
  template:
    metadata:
      labels:
        app: "aksdemo-19f0"
    spec:
      containers:
        - name: "aksdemo-19f0"
          image: "acrdemo1180.azurecr.io/aksdemo"
          ports:
          - containerPort: 80